stages:
  - build
  - deploy

build:server:
  stage: build
  tags:
    - bash_builder
  script:
    - docker login -u git -p $REGISTRY_PASSWORD docker.internal.feel.ac.cn
    - docker build -t docker.internal.feel.ac.cn/mp-analyzer/wxss-validator:$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - docker push docker.internal.feel.ac.cn/mp-analyzer/wxss-validator:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

deploy:server:
  stage: deploy
  tags:
    - dev
  script:
    - docker login -u git -p $REGISTRY_PASSWORD docker.internal.feel.ac.cn
    - docker-compose pull
    - docker-compose down || exit_code=$?
    - if [ $exit_code -ne 0 ]; then echo "new to start"; fi; 
    - docker-compose up -d;
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: devlopment_server
    url: http://mp-analyzer-$CI_ENVIRONMENT_SLUG.web
