stages:
  - build

build:server:
  stage: build
  tags:
    - bash_builder
  script:
    - docker login -u git -p $REGISTRY_PASSWORD docker.internal.feel.ac.cn
    - docker build -t docker.internal.feel.ac.cn/mp-analyzer/wxss-validator:latest .
    - docker push docker.internal.feel.ac.cn/mp-analyzer/wxss-validator:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
